### ISSUE TITLE
[scienti_sources]

### ISSUE THREAD

**Issue by omazapa** [colav/Kahi_plugins#58]
```
Plugin scienti_sources failed
Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi/Kahi.py", line 126, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.11/site-packages/kahi_scienti_sources/Kahi_scienti_sources.py", line 247, in run
    print("Processing {} database".format(config["database_name"]))
                                          ~~~~~~^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by muzgash** [comment]
Please provide the yaml file with each issue so we can check if there is any error on it.

**Comment by omazapa** [comment]
The file is this one for all, I am just commenting sections to perform the tests.

```
config:
  database_url: localhost
  database_name: kahi_test
  log_database: kahi_test
  log_collection: log
workflow:
  doaj_sources:
    database_url: localhost:27017
    database_name: doaj
    collection_name: stage
  scimago_sources:
    file_path: 
      - ./scimago/scimagojr 1999.csv
      # - ./scimago/scimagojr 2000.csv
      # - ./scimago/scimagojr 2001.csv
      # - ./scimago/scimagojr 2002.csv
      # - ./scimago/scimagojr 2003.csv
      # - ./scimago/scimagojr 2004.csv
      # - ./scimago/scimagojr 2005.csv
      # - ./scimago/scimagojr 2006.csv
      # - ./scimago/scimagojr 2007.csv
      # - ./scimago/scimagojr 2008.csv
      # - ./scimago/scimagojr 2009.csv
      # - ./scimago/scimagojr 2010.csv
      # - ./scimago/scimagojr 2011.csv
      # - ./scimago/scimagojr 2012.csv
      # - ./scimago/scimagojr 2013.csv
      # - ./scimago/scimagojr 2014.csv
      # - ./scimago/scimagojr 2015.csv
      # - ./scimago/scimagojr 2016.csv
      # - ./scimago/scimagojr 2017.csv
      # - ./scimago/scimagojr 2018.csv
      # - ./scimago/scimagojr 2019.csv
      # - ./scimago/scimagojr 2020.csv
      # - ./scimago/scimagojr 2021.csv
      # - ./scimago/scimagojr 2022.csv
  # scienti_sources:
  #     database_url: localhost:27017
  #     database_name: scienti_111
  #     collection_name: products
  #   #- database_url: localhost:27017
  #   #  database_name: scienti_uec_2022
  #   #  collection_name: product
  #   #- database_url: localhost:27017
  #   #  database_name: scienti_univalle_2022
  #   #  collection_name: product
  openalex_sources:
    database_url: localhost:27017
    database_name: openalex
    collection_name: venues
    num_jobs: 20
  # openalex_subjects:
  #   database_url: localhost:27017
  #   database_name: openalex
  #   collection_name: concepts
  #   num_jobs: 20
  # ror_affiliations:
  #   database_url: localhost:27017
  #   database_name: ror
  #   collection_name: stage
  #   num_jobs: 20
  # staff_udea_affiliations:
  #   file_path: ./udea/Base de Datos profesores 2019_con_clasificación de Colciencias.xlsx
  # wikipedia_affiliations:
  #   tasks:
  #     - names
  #   num_jobs: 5
  #   verbose: 5
  # scienti_affiliations:
  #   databases:
  #     - database_url: localhost:27017
  #       database_name: scienti_111
  #       collection_name: products
  #   verbose: 2
  #   #- database_url: localhost:27017
  #   #  database_name: scienti_uec_2022
  #   #  collection_name: product
  #   #- database_url: localhost:27017
  #   #  database_name: scienti_univalle_2022
  #   #  collection_name: product
  minciencias_opendata_affiliations: #MISSING DATA
    file_path: ./abiertos_minciencias/3-Grupos_de_Investigaci_n_Reconocidos.csv
  # staff_udea_person:
  #   file_path: ./udea/Base de Datos profesores 2019_con_clasificación de Colciencias.xlsx
  # scienti_person:
  #   databases:
  #     - database_url: localhost:27017
  #       database_name: scienti_111
  #       collection_name: products
  #   verbose: 2
  #   #- database_url: localhost:27017
  #   #  database_name: scienti_uec_2022
  #   #  collection_name: product
  #   #- database_url: localhost:27017
  #   #  database_name: scienti_univalle_2022
  #   #  collection_name: product
  # minciencias_opendata_person:
  #   researchers: ./abiertos_minciencias/2-Investigadores_Reconocidos_por_convocatoria.csv
  #   cvlac: ./abiertos_minciencias/4-cvlac.csv
  #   groups_production: ./abiertos_minciencias/1-Producci_n_Grupos_Investigaci_n.csv
  #   num_jobs: 20
  # openalex_person:
  #   database_url: localhost:27017
  #   database_name: openalexco
  #   collection_name: authors
  #   num_jobs: 4
  # works:
  #   num_jobs: 5
  #   verbose: 5
  #   openalex:
  #     database_url: localhost:27017
  #     database_name: openalexco
  #     collection_name: works
  #   scopus:
  #     database_url: localhost:27017
  #     database_name: scopus_colombia
  #     collection_name: stage
  #   wos:
  #     database_url: localhost:27017
  #     database_name: wos_colombia
  #     collection_name: stage
  #   scholar:
  #     database_url: localhost:27017
  #     database_name: scholar_colombia
  #     collection_name: stage
  #   scienti:
  #     database_url: localhost:27017
  #     database_name: scienti_111
  #     collection_name: products
  #   puntaje:
  #     file_path: ./udea/produccion 2018-2022 al 27 oct 2022.xlsx
```
